import type { Metadata } from "next";
import Navbar from "@/components/Navbar/Navbar";
import { Playfair_Display } from "next/font/google"
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/toaster"
import { auth } from "@/app/auth"
import NextAuthProvider from "./providers/NextAuthProvider"


export const metadata: Metadata = {
  title: "Thvani",
  description: "Generated by create next app",
};

const font = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700']
})

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  return (
    <html lang="en">
      <body className={font.className}>
        <NextAuthProvider session={session}>
          <StoreProvider>
            <Navbar />
            {children}
            <Footer />
            <Toaster />
          </StoreProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
