import type { Metadata } from "next";
import Navbar from "@/components/Navbar/Navbar";
import {Playfair_Display } from "next/font/google"
import "./globals.css";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Thvani",
  description: "Generated by create next app",
};

const font = Playfair_Display({
  subsets:['latin'],
  weight:['400','700']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
